name: Install, Build, Lint and Test
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run Lint
        run: npm run lint
      - name: Run Tests
        run: npm run test:coverage:silent
